### ISSUE TITLE
pub/sub sometimes  timeout 

### ISSUE THREAD

**Issue by Hsuwen** [dapr/dotnet-sdk#1092]
I am using dapr's pub/sub (which is published using rabbitMQ and runs in k8s). However, sometimes, the **PublishEventAsync** method times out, as shown in the figure.

If the CancellationTokenSource is not set, an error HttpClient timeout of **100** seconds will be reported in **PublishEventAsync**.
<img alt="pubsub-code" src="https://resource01-hw.cdn.yiofong.com/pubsub-code.png" />

What I can confirm is that rabbitMQ is normal when the error 'timeout' is reported. Moreover, the message was successfully pushed to rabbitMQ and consumed.
Every time I encounter this exception, it seems like I can only restart rabbitMQ and everything will recover.

I don't have any ideas about this mistake. Can someone provide me with some help? 
**Thanks!**

**Comment by Hsuwen** [comment]
yaml of rabbitMQ
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: myns
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11-management
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 768M
            limits:
              cpu: 500m
              memory: 768M
          ports:
          - name: server
            containerPort: 5672
          - name: admin
            containerPort: 15672
          env:
          - name: RABBITMQ_DEFAULT_VHOST
            value: /
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: mykey
                key: rabbitmq_user
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: mykey
                key: rabbitmq_pass
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-data
            subPath: rabbitmq
      imagePullSecrets:
        - name: mypkg
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-admin
  namespace: silkroad
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-server
  namespace: silkroad
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
```

**Comment by Hsuwen** [comment]
component of Dapr
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: myns
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: myconn
      key: rabbitmq_conn
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: true
  - name: autoAck
    value: false
  - name: deliveryMode
    value: 2
  - name: requeueInFailure
    value: true
  - name: prefetchCount
    value: 2
  - name: publisherConfirm
    value: true
  - name: reconnectWait
    value: 0
  - name: concurrencyMode
    value: parallel
  - name: backOffPolicy
    value: exponential
  - name: backOffInitialInterval
    value: 1s
  - name: backOffMaxInterval
    value: 180s
  - name: backOffMaxRetries
    value: 15
  - name: enableDeadLetter
    value: true
  - name: exchangeKind
    value: fanout
auth:
    secretStore: kubernetes
```
