### ISSUE TITLE
how to load the  azureCertificateFile 

### ISSUE THREAD

**Issue by hernandoz** [dapr/dotnet-sdk#1232]
## Ask your question here
Hi I am having problems loading the  azureCertificateFile pfx file for the azure keyVault component locally , I can get the file to load . 

what's the right format to add on the path value ?

storesecret.yaml 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: coresecretstore

spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: srmdev-container-core
  - name: azureTenantId
    value: 22312560-20c8-4884-8c1d-82cb2dea0c91
  - name: azureClientId
    value : 0b3f774c-7697-4aa6-a8b5-1ddf1f0cf5dc
  - name: azureCertificateFile
    value: \srmdev-container-core-SRMDEVContainerKeyVaultAccess-20240209.pfx
```

Error
`time="2024-02-09T15:11:51.416171264Z" level=error msg="Error getting secret: ChainedTokenCredential: failed to acquire a token.\nAttempted credentials:\n\tmanaged identity\n\tAzureCLICredential: fork/exec /bin/sh: no such file or directory" app_id=project-reporting-service instance=5deedd416f9f scope=dapr.runtime type=log ver=1.12.0`

the certificate is located in the same folder where the yaml is. 

Project Folder 

![image](https://github.com/dapr/dotnet-sdk/assets/1914468/041dcdd9-74cf-4a46-8811-b0195e74db24)

Thanks
