### ISSUE TITLE
Update the holopin.yml to use the sdk badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/dotnet-sdk#1270]
Update the `.github/holopin.yml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqfdv4x24910fl5n4iwu5oa) for this repo:

```yaml
organization: dapr
defaultSticker: clrqfdv4x24910fl5n4iwu5oa
stickers:
  -
    id: clrqfdv4x24910fl5n4iwu5oa
    alias: sdk-badge
```

The old information in the yml file can be removed.

> Note that all commits need a DCO/sign-off, [more info in docs](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work).

Once this is in place, maintainers can award contributors with [this badge](https://www.holopin.io/sticker/clrqfdv4x24910fl5n4iwu5oa) via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---

Please label this as a __good first issue__.
