### ISSUE TITLE
GetSecretAsync - Error connecting to subchannel.

### ISSUE THREAD

**Issue by sohlae** [dapr/dotnet-sdk#1492]
I have a Secret Store component defined below and is being used by our Azure Kubernetes Service cluster. The AKS node pool has been given access to Azure Key Vault using its Managed Identity so we didn't have to add a client ID and client secret in the component's metadata property. 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: keyvault-secretstore
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "kv-name"
```

We noticed an intermittent issue where at times `GetSecretAsync()` will not be able to get the secret and will throw an exception. Sometimes it happens, sometimes it does not. Is there a way for us to investigate this issue further?

Error Message: Secret operation failed: the Dapr endpoint indicated a failure. See InnerException for details.. Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it." 

```c#
try
{
    var secret = await _daprClient.GetSecretAsync(secretStoreName, "database-connection-string");
}

catch (Exception exception)
{
    Console.WriteLine($"Unable to extract the value of the database-connection-string secret. {exception.Message}. {exception.InnerException?.Message}");
}
```
