### ISSUE TITLE
Sidecar inject failed but app start  correct. [actor]

### ISSUE THREAD

**Issue by zivfuture** [dapr/dotnet-sdk#667]
I have a simple order api:
```
//OrderController.cs
[HttpPost("productchanged")]
[Topic(DaprPubSubName, "productchanged")]
public async Task ProductChanged(ProductChangedEvent @event)
{
       var orders= await client.GetStateAsync<List<Order>>(STORE_NAME, STATE_ORDER_KEY);
       ...
       await client.SaveStateAsync(STORE_NAME, STATE_ORDER_KEY, orders);
}

//OrderProcessActor.cs
public class OrderProcessActor : Actor, IOrderProcessActor
{
    public OrderProcessActor(ActorHost host):base(host)   {   }
    public Task<Order> OrderProcess(Product product, Order order)
    {
        //...
        return Task.FromResult(order);
    }
}


//Startup.cs
public void ConfigureServices(IServiceCollection services)
{
      services.AddActors(x=>
      {
            x.Actors.RegisterActor<OrderProcessActor>();
       });
       services.AddControllers().AddDapr();
}
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseRouting();
    app.UseAuthorization();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapSubscribeHandler();
        endpoints.MapActorsHandlers();
        endpoints.MapControllers();
    });
}
```
```yaml
#orderapi.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
      annotations:
        dapr.io/log-level: "debug"
        dapr.io/enabled: "true"
        dapr.io/app-id: "order"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: order
        image: order:1.0
        imagePullPolicy: Never
        ports:
        - name: web
          containerPort: 80

        env:
        - name: POD_IP 
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

#pubsub-component.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
```

I got those errors below when i deployed it in kubernetes? 
-----kubectl logs  order-57f79bc797-4fzns  daprd: 
![image](https://user-images.githubusercontent.com/49356505/116814468-b7f4a700-ab8b-11eb-84f8-d65beff2ec70.png)

---- kubectl logs order-57f79bc797-4fzns  orde:
![image](https://user-images.githubusercontent.com/49356505/116814516-ef635380-ab8b-11eb-940e-028d88f728fe.png)

-----kubectl get po:
![image](https://user-images.githubusercontent.com/49356505/116814549-220d4c00-ab8c-11eb-9ac0-c1ab1472c3a3.png)

-----curl 10.100.104.23/dapr/subscribe ,  As you see the api returned correct data of subscribe.
![image](https://user-images.githubusercontent.com/49356505/116814607-6862ab00-ab8c-11eb-900f-9294b8fa65eb.png)

![image](https://user-images.githubusercontent.com/49356505/116814763-fa6ab380-ab8c-11eb-8615-3fedb84a7e7a.png)

By the way.  the state component  works fine.
Did I make any mistakes?

**Comment by zivfuture** [comment]
well.   it solved. 

it works fine when i add this key in  statestore component  metadata.   the errors confused me.  

##### statestore.yaml
```yaml
metadata
- name: actorStateStore
  value: "true"
```
