### ISSUE TITLE
Dapr Serialization Error 

### ISSUE THREAD

**Issue by zivfuture** [dapr/dotnet-sdk#668]
## In what area(s)? 
> /area runtime  

## What version of Dapr?
> 1.1.x  

## Expected Behavior
publish event, and recive event

## Actual Behavior
publish event success, but receive event failed

## Steps to Reproduce the Problem
1. there is  one api project named  "product" (appid),  code as below:
```c#
//ProductController.cs
[HttpGet("ChangeProduct")]
public async Task ChangeProduct()
{
    await eventBus.PublishAsync("productchanged", new { ID=2, Price=30m});
    logger.LogInformation("success");
}

//EventBus.cs
public async Task PublishAsync<TIntegrationEvent>(string topic, TIntegrationEvent @event)
{
    await client.PublishEventAsync("rabbitmq-pubsub", topic, @event);
}
```
2. another api project named "order" 
```c#
[HttpPost("productchanged")]
[Topic(DaprPubSubName, "productchanged")]
public async Task ProductChanged(Product @event)
{
        _logger.LogInformation("received event");
        //do something
       _logger.LogInformation("finished");
}

//Product.cs
public class Product
{
    public int ID { get; set; }
    public decimal Price { get; set; }
}
```
3. pubsub component yaml:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://user:xxx@rabbitmq:5672"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: deliveryMode
    value: "0"
  - name: requeueInFailure
    value: "false"
  - name: prefetchCount
    value: "0"
  - name: reconnectWait
    value: "0"
  - name: concurrencyMode
    value: parallel
```
4. publish success:
![image](https://user-images.githubusercontent.com/49356505/116892604-8f8bac00-ac62-11eb-967a-7496c2617427.png)

4. i get some error from order api:
logs for daprd(sidecar)
![image](https://user-images.githubusercontent.com/49356505/116892681-a8945d00-ac62-11eb-915b-d9af8355d43f.png)
