### ISSUE TITLE
app returned http status code 500 from subscription endpoint

### ISSUE THREAD

**Issue by latala43** [dapr/dotnet-sdk#733]
I try to find a way to use Dapr in my development machine.
- Windows 10
-  Docker Desktop
- WSL 2
- Docker Compose
- Visual Studio 2019
- Asp.Net Core ....

The problem that I'm facing is clear that my existing solution is running in HTTPS scheme. So, I tried to play with Sentry to simulate what a Kubernate do with auto generated certs.

```
sentry:
        container_name: "dapr.sentry"
        image: "daprio/sentry:latest"
        command: ["./sentry", "-issuer-credentials", "/certs", "-config", "/configuration/dapr-config.yaml"]
        volumes:
            - "./dapr/certs/:/certs"
            - "./dapr/configuration/:/configuration"
        depends_on:
            - placement
```
The certificates is generated successfully. But still I receive the error:
```
app returned http status code 500 from subscription endpoint
```

I know it is not an issue, but there is a lake in the documentation.
I think this error is related to https. Am I correct?
How to fix it using https?
