### ISSUE TITLE
Maybe bug about input binding

### ISSUE THREAD

**Issue by JhouXerox** [dapr/dotnet-sdk#736]
## Expected Behavior
I was following the doc [here](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/bindings) to try the binding building block.
the expected behavior is I can get the message which is published by CameraSimulation.

## Actual Behavior

![image](https://user-images.githubusercontent.com/24403596/129209890-34fa0350-8515-4ba7-8b05-58723eefafef.png)
the MQTTTrafficControlService can publish the message to mosquitto mqtt broker.and I can view message by MQTTX.
![image](https://user-images.githubusercontent.com/24403596/129210052-2c3c339d-2f74-44b5-99c8-fba35c51b3e0.png)

but I can't get my custom payload in my endpoint url.
I try to get everything I can.I only get this.
![image](https://user-images.githubusercontent.com/24403596/129210620-ee42ffb6-f5d9-4a03-a35b-e39d1eec3e92.png)

I can't find my payload in zipkin too.
```json
[
    {
        "traceId": "2f8d51a900021e2235385801b1697365",
        "id": "d74398b8691da7cc",
        "kind": "SERVER",
        "name": "bindings/entrycam",
        "timestamp": 1628777000054569,
        "duration": 1721,
        "localEndpoint": {
            "serviceName": "trafficcontrolservice",
            "ipv4": "192.168.1.3"
        },
        "tags": {
            "db.connection_string": "POST /entrycam",
            "db.name": "entrycam",
            "db.system": "bindings",
            "opencensus.status_description": "OK",
            "rpc.service": "Dapr"
        }
    }
]
```

## Steps to Reproduce the Problem
Heres my input-binding yaml file.
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: entrycam
  namespace: dapr-trafficcontrol
spec:
  type: bindings.mqtt
  version: v1
  metadata:
    - name: url
      value: mqtt://localhost:1883
    - name: topic
      value: trafficcontrol/entrycam
    - name: consumerID
      value: "{uuid}"
    - name: qos
      value: 1
    - name: retain
      value: "false"
    - name: cleanSession
      value: "false"
scopes:
  - trafficcontrolservice
```

## Release Note
Do not use dynamic type.

And in the model need to use property.
![image](https://user-images.githubusercontent.com/24403596/129298891-e1d5e4c0-46bb-40f5-8a5c-221f1ecd81f6.png) it was  variable before so System.Text.Json can't deserialize successful. only `{}`.
now the function like this 
![image](https://user-images.githubusercontent.com/24403596/129299107-5c907518-971b-4b47-a8a5-bdcc5c9a6ffa.png)
