### ISSUE TITLE
Placement Service not called for Actor Using Dotnet SDK and Docker-Compose

### ISSUE THREAD

**Issue by darthmolen** [dapr/dotnet-sdk#813]
When using the DotNetCore 6,  DotNet SDK, Docker Compose, custom bridge, the placement service never gets called.

docker-compose

```
version: '3.4'

services:
  rentalpropertyservice:
    image: ${DOCKER_REGISTRY-}rentalpropertyservice
    build:
      context: .
      dockerfile: K8S_Actor_API/Dockerfile
    ports: 
    - 50010:50001
    - "5124"
    depends_on:
      - dapr.statestores.redis
      - dapr.service.placement
    networks:
      - dapr

  
  rentalpropertyservice-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "rentalpropertyservice", "-app-port", "5124", "-placement-host-address", "dapr.statestores.placement:50020", "-components-path", "/components"  ]
    volumes:
      - "./components/:/components"
    depends_on:
      - rentalpropertyservice
    network_mode: "service:rentalpropertyservice"

  dapr.service.placement:
    container_name: dapr.statestores.placement
    image: "daprio/dapr"
    command: ["./placement", "-port", "50020"]
    ports:
      - "50020:50020"
    networks:
      - dapr

  dapr.statestores.redis:
    container_name: dapr.statestores.redis
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - dapr
   
networks:
  dapr:
```

program.cs:
```
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateBootstrapLogger();

Log.Information("Starting up");


var builder = WebApplication.CreateBuilder(args);
builder.Host.UseSerilog((ctx, logger) => { logger.ReadFrom.Configuration(ctx.Configuration);  });


// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddDaprClient(); ;
builder.Services.AddActors(options => {
    options.Actors.RegisterActor<RentalPropertyActor.Actors.RentalPropertyActor>();
});

var app = builder.Build();

app.UseSerilogRequestLogging();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapActorsHandlers();


app.MapGet("/MarkPropertyReady/{OwnerId}/{PropertyId}/{UnitId}", async (string OwnerId, string PropertyId, string UnitId) => {

    if (string.IsNullOrWhiteSpace(OwnerId) || string.IsNullOrWhiteSpace(PropertyId))
        return Results.Problem("Owner Id or Property Id not filled out");

    var actorProxy = GetRentalPropertyActorAsync(OwnerId, PropertyId, UnitId);

    // Get UnitInfo, PropertyComplex from repo

    await actorProxy.PropertyReadyAsync(OwnerId, PropertyId, new RentalPropertyService.Model.UnitInfo(), new RentalPropertyService.Model.PropertyComplex());

    return Results.Ok();
})
    .WithName("MarkPropertyReady");
try
{
    Log.Information("Starting Webhost...");
    app.Run();

}
catch (Exception ex) 
{
    Log.Fatal(ex, "Unhandled Exception");
}
finally 
{
    Log.Information("Shut Down Complete");
    Log.CloseAndFlush();
}

IRentalPropertyActor GetRentalPropertyActorAsync(string OwnerId, string PropertyId, string UnitId)
{
    return ActorProxy.Create<IRentalPropertyActor>(RentalPropertyActor.Actors.RentalPropertyActor.GetActorId(OwnerId, PropertyId, UnitId), nameof(RentalPropertyActor));
}
```

when calling the actor endpoint via swagger, it says "Dapr.DaprApiException: actor runtime is not configured". Also, in the placement service, there is no log entries about a member update count. However, calling the /dapr/config on the service shows an entry, `{"entities":["RentalPropertyActor"],"reentrancy":{"enabled":false}}`

Code works when using the self-hosted mode.

`dapr run --app-id rentalpropertyservice --app-port 5124 --dapr-http-port 3500 dotnet run`
