### ISSUE TITLE
Duplications in running Dapr events

### ISSUE THREAD

**Issue by AndrewSafwatFrancis** [dapr/dotnet-sdk#932]
Hi all, I have an issue with dapr grpc events. **Sometimes **the events runs multiple times. I'm using redis and in another env. I'm using azure queues as I thought that the issue was related to redis but I have the same issue.
I created a sample project the simulate what I'm doing. Here is the project [](https://github.com/AndrewSafwatFrancis/DaprTest)
and here is the settings in dapr pubsub.yml file
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: value
  - name: redisPassword
    value: value
```
	
If you can support, and tell me what is the issue or what's missing, it will be great as I'm stuck on it.
